# This file contains common properties shared across all profiles.
# Spring Boot will always load this file first.
springdoc:
  default-produces-media-type: application/json

application:
  file:
    uploads:
      media-output-path: ./uploads
  origins:
    allowed: http://localhost:4200, http://app-ui:4200, http://keycloak:9090