spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsapp_clone
    username: bamoya
    password: bamoya
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/whatsapp-clone

springdoc:
  default-produces-media-type: application/json


application:
  file:
    uploads:
      media-output-path: ./uploads


